.PHONY: build run down

build:
				docker compose build --no-cache

run_app:
				docker compose run --rm agent-langgraph

run:
				docker compose up -d

stop:
				docker compose stop

down:
				docker compose down