.PHONY: build run run_agent down

build:
				docker compose build --no-cache

run_agent:
				docker compose run agent

run:
				docker compose up -d

stop:
				docker compose stop

down:
				docker compose down
