[project]
name = "agent-quickstart"
version = "0.1.0"
description = "LangChain Playground"
readme = "README.md"
authors = [
    { name = "karatejb", email = "13954352+KarateJB@users.noreply.github.com" }
]
requires-python = ">=3.11"
dependencies = [
    "deepagents>=0.7.13",
    "langchain>=1.4.0",
    "langchain-google-genai>=4.4.0",
]

[project.scripts]
langchain-playground = "agent_quickstart:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"